<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJJRGR7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJJRGR7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDJJRGR7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDJJRGR7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDJJRGR7\App_KernelDevDebugContainer([
    'container.build_hash' => 'DJJRGR7',
    'container.build_id' => '1d5f4228',
    'container.build_time' => 1607512992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJJRGR7');
