<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKXu7W9X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKXu7W9X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKXu7W9X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKXu7W9X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKXu7W9X\App_KernelDevDebugContainer([
    'container.build_hash' => 'KXu7W9X',
    'container.build_id' => 'dc276381',
    'container.build_time' => 1607198049,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKXu7W9X');
